server:
  port: 8080
  servlet:
    context-path: /api/dega/elastic


spring:
  application:
    name: elastic-search

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE

elastic:
  cluster:
    username: elastic
    password: hU1JteGUr=*5PpL4jQwQ
    host: *******
    port: 9200

